## TRANSFORM FULL EXTRACTION DATA

In [3]:
import pandas as pd

# Load full extracted data
df_full = pd.read_csv('custom_data.csv')

# 1. Clean: Drop missing values and duplicates
df_full.dropna(inplace=True)
df_full.drop_duplicates(inplace=True)

# 2. Enrich: Create total_contribution column
df_full['total_contribution'] = (
    df_full['points_scored'] + df_full['assists'] + df_full['rebounds']
)

# 3. Structure: Convert date columns to datetime
df_full['match_date'] = pd.to_datetime(df_full['match_date'])
df_full['last_updated'] = pd.to_datetime(df_full['last_updated'])

# Save transformed data
df_full.to_csv('transformed_full.csv', index=False)

df_full.head()

,player_id,player_name,team,match_date,points_scored,assists,rebounds,last_updated,total_contribution
0,P001,Sherry Miles,Falcons,2025-04-24,25,2,12,2025-04-27,39
1,P002,Gina Campbell,Falcons,2025-06-08,36,14,17,2025-06-08,67
2,P003,Holly Williams,Wolves,2025-06-09,29,11,14,2025-06-14,54
3,P004,Charles Dixon,Tigers,2025-04-20,10,0,3,2025-04-25,13
4,P005,Travis Moore,Eagles,2025-04-20,19,5,16,2025-04-22,40

## TRANSFORM INCREMENTAL DATA

In [4]:
# Load incremental extracted data
df_incremental = pd.read_csv('extracted_incremental.csv')

# 1. Clean
df_incremental.dropna(inplace=True)
df_incremental.drop_duplicates(inplace=True)

# 2. Enrich
df_incremental['total_contribution'] = (
    df_incremental['points_scored'] + df_incremental['assists'] + df_incremental['rebounds']
)

# 3. Structure
df_incremental['match_date'] = pd.to_datetime(df_incremental['match_date'])
df_incremental['last_updated'] = pd.to_datetime(df_incremental['last_updated'])

# Save transformed incremental data
df_incremental.to_csv('transformed_incremental.csv', index=False)

df_incremental.head()

,player_id,player_name,team,match_date,points_scored,assists,rebounds,last_updated,total_contribution
0,P002,Gina Campbell,Falcons,2025-06-08,36,14,17,2025-06-08,67
1,P003,Holly Williams,Wolves,2025-06-09,29,11,14,2025-06-14,54
2,P008,David Wilson,Eagles,2025-06-03,26,6,13,2025-06-07,45
3,P009,David Collier,Sharks,2025-05-28,24,7,4,2025-05-31,35
4,P010,Stephanie Hill,Tigers,2025-06-08,18,11,14,2025-06-11,43